In [110]:
import matplotlib.pyplot as plt
from importlib import reload
import numpy as np
import networkx as nx

import model
import agents, activation_regimes



### Standard Model Agent

In [111]:
m = model.Model(1234, 5, ('scale_free', (10, 5)), agents.StandardModelAgent,
activation_regimes.Synchronous, None)
m.run_model()

In [112]:
m.raw_data

array([[ 0.26674687,  0.31954504,  0.24972044,  0.28651674,  0.2860963 ,
         0.28612343],
       [ 0.62027169,  0.73552378,  0.46701588,  0.59512888,  0.594301  ,
         0.59475109],
       [-0.92707301,  0.10699845,  0.11731784,  0.11501528,  0.10641301,
         0.1100523 ],
       [-0.26051624, -0.1765958 , -0.17578088, -0.17669342, -0.17751982,
        -0.1771301 ],
       [-0.67206201, -0.67206201, -0.67206201, -0.67206201, -0.67206201,
        -0.67206201],
       [ 0.58365336,  0.51755742,  0.52093201,  0.50491956,  0.51343544,
         0.51348978],
       [-0.02303976,  0.1010552 ,  0.08948937,  0.08685262,  0.08549912,
         0.08676896],
       [ 0.75409407,  0.7110334 ,  0.69709838,  0.69481879,  0.69761835,
         0.69778022],
       [ 0.80109296, -0.03637269,  0.41661255,  0.41735554,  0.414535  ,
         0.41236187],
       [ 0.13619162, -0.5037778 , -0.33947838, -0.33793335, -0.33831663,
        -0.33968578]])

In [113]:
ag = m.agents[0]
ag.unique_id, ag.a_ii

(0, 0.1110233443550892)

In [114]:
ag.o_i1

0.26674687212207493

In [115]:
ag.w_j

array([0.27035992, 0.72964008])

In [116]:
m.agents[5].o_i1, m.agents[8].o_i1

(0.5836533623966913, 0.8010929584256852)

In [117]:
ag.neighbor_ids

array([5, 8], dtype=int64)

In [118]:
0.111023*(.27035*.58365 + .72964*.80109) + (1-0.111023)*0.26675

0.3195466640290573

In [119]:
m.raw_data[0, 1]

0.31954503776732307

thus Agent 0 correctly updated on its first activation

In [120]:
ag.a_ii * np.dot(ag.w_j, [0.517557, -0.036373]) + ag.biased_initial_opinion

0.24972039822812725

In [121]:
m.raw_data[0, 2]

0.24972043556086088

and again on its next (the neighbor o_is were read manually from m.raw_data)

### Nonlinear agent

In [122]:
m = model.Model(1234, 5, ('scale_free', (10, 5)), agents.NonlinearAgent,
activation_regimes.Synchronous, None)
m.run_model()

In [123]:
m.raw_data

array([[ 0.26674687,  0.03580504,  0.04567856,  0.04737176,  0.04749788,
         0.04748709],
       [ 0.62027169,  0.23913959,  0.34012607,  0.34657286,  0.34705834,
         0.34701778],
       [-0.92707301,  0.34276473,  0.38857937,  0.38402058,  0.3842512 ,
         0.38425685],
       [-0.26051624,  0.04759677,  0.05790978,  0.05740075,  0.05742668,
         0.05742713],
       [-0.67206201, -0.67206201, -0.67206201, -0.67206201, -0.67206201,
        -0.67206201],
       [ 0.58365336,  0.10357719,  0.11822923,  0.11674447,  0.11666426,
         0.1166552 ],
       [-0.02303976,  0.11068105,  0.14380541,  0.14318206,  0.14322885,
         0.14323087],
       [ 0.75409407,  0.04253141,  0.04492277,  0.04442357,  0.04440814,
         0.04440433],
       [ 0.80109296,  0.45234026,  0.36104557,  0.35523364,  0.35580762,
         0.35578459],
       [ 0.13619162,  0.50294727,  0.45666936,  0.45488814,  0.45506086,
         0.45505209]])

In [124]:
ag = m.agents[0]
ag.unique_id, ag.b_i0

(0, 0.1110233443550892)

In [125]:
m.raw_data[0, 0]

0.26674687212207493

In [126]:
ag.w_j, ag.neighbor_ids

(array([0.27035992, 0.72964008]), array([5, 8], dtype=int64))

In [127]:
0.111023 / (1 + np.exp(.27035*.58365 + .72964*.80109))

0.035805143860342115

In [128]:
m.raw_data[0, 1]

0.03580503847709889

thus Agent 0 correctly updated on its first activation

In [129]:
ag.b_i0 / (1 + np.exp(np.dot(ag.w_j, [0.10357719, 0.45234026])))

0.04567855674969885

In [130]:
m.raw_data[0,2]

0.04567855673816483

and again on its next (the neighbor o_is were read manually from m.raw_data)

### Similarity bias agent

In [131]:
m = model.Model(1234, 5, ('scale_free', (10, 5)), agents.SimilarityBiasAgent,
activation_regimes.Synchronous, None)
m.run_model()

In [132]:
m.raw_data

array([[ 0.26674687,  0.26674687,  0.26674687,  0.26674687,  0.26674687,
         0.26674687],
       [ 0.62027169,  0.71068232,  0.75588764,  0.74543549,  0.74020941,
         0.68781377],
       [-0.92707301, -0.92707301, -0.92707301, -0.92707301, -0.92707301,
        -0.92707301],
       [-0.26051624, -0.26051624, -0.26051624, -0.26051624, -0.26051624,
        -0.26051624],
       [-0.67206201, -0.67206201, -0.67206201, -0.67206201, -0.67206201,
        -0.67206201],
       [ 0.58365336,  0.60196252,  0.63541812,  0.4510825 ,  0.4510825 ,
         0.4510825 ],
       [-0.02303976, -0.02303976, -0.02303976, -0.02303976, -0.02303976,
        -0.02303976],
       [ 0.75409407,  0.66887371,  0.63541812,  0.63541812,  0.63541812,
         0.68781377],
       [ 0.80109296,  0.80109296,  0.73498334,  0.73498334,  0.73498334,
         0.73498334],
       [ 0.13619162,  0.13619162,  0.13619162,  0.13619162,  0.13619162,
         0.13619162]])

In [133]:
ag = m.agents[0]
ag.unique_id, ag.o_i1

(0, 0.26674687212207493)

In [134]:
import constants
constants.SIMILARITY_BIAS_EPSILON

0.4

In [135]:
ag.neighbor_ids

array([5, 8], dtype=int64)

In [136]:
m.raw_data[(5,8),0]

array([0.58365336, 0.80109296])

In [137]:
np.abs(m.raw_data[(5,8),0] - m.raw_data[0, 0]) < constants.SIMILARITY_BIAS_EPSILON

array([ True, False])

so agent 5 is close enough to interact, but 8 is not...who was the random selection for the first activation?

In [138]:
ag.neighbor_ids[ag.neighbor_indexes_over_time_for_adoption[0]]

8

agent 8 is selcted but too far away, so agent 0 should not change opinion

In [139]:
m.raw_data[0, (0, 1)]

array([0.26674687, 0.26674687])

thus Agent 0 correctly was not influenced

In [140]:
ag.neighbor_indexes_over_time_for_adoption

array([1, 1, 1, 1, 1, 0])

In [141]:
ag.w_j

array([0.27035992, 0.72964008])

due to 8's high weight (ag.w_j), it was selected for interaction every step during the run, but never came close enough to interact

In [142]:
np.abs(ag.o_i1 - np.min(m.raw_data[8])), constants.SIMILARITY_BIAS_EPSILON

(0.4682364641340695, 0.4)

In [143]:
ag = m.agents[1]
ag.unique_id, ag.o_i1

(1, 0.6202716875330976)

In [144]:
ag.neighbor_ids

array([7, 8], dtype=int64)

In [145]:
m.raw_data[(7, 8), 0]

array([0.75409407, 0.80109296])

In [146]:
np.abs(m.raw_data[(7,8),0] - m.raw_data[1, 0]) < constants.SIMILARITY_BIAS_EPSILON

array([ True,  True])

agent 1 can interact with either neighbor

In [147]:
ag.neighbor_ids[ag.neighbor_indexes_over_time_for_adoption[0]]

8

agent 8 is selected and is close enough to interact

In [148]:
ag.o_i1 + constants.SIMILARITY_BIAS_MU * (0.80109-ag.o_i1)

0.7106808437665488

In [149]:
m.raw_data[1,1]

0.7106823229793914

and Agent 1 was correctly influenced by agent 8

In [150]:
m.agents[9].neighbor_ids

array([2, 4, 6], dtype=int64)

In [151]:
np.abs(m.raw_data[(2,4,6),0] - m.raw_data[9, 0]) < constants.SIMILARITY_BIAS_EPSILON

array([False, False,  True])

In [152]:
m.agents[9].w_j, m.agents[9].neighbor_indexes_over_time_for_adoption

(array([0.21126494, 0.77885848, 0.00987658]), array([1, 1, 0, 0, 1, 1]))

In [153]:
m.raw_data[9]

array([0.13619162, 0.13619162, 0.13619162, 0.13619162, 0.13619162,
       0.13619162])

agent 9 does not change opinion during the run. note that at the start, its first two neighbors are too far away to interact, and due to its weights, it only interacts with them. agents 2 and 4 also happen to not change opinion during the run: 2 starts off at a very negative value while its neighbors are positive, and 4 has no neighbors.

In [154]:
m.agents[4].neighbor_ids

array([], dtype=int64)

### Attractive repulsive agent

In [155]:
m = model.Model(1234, 5, ('scale_free', (10, 5)), agents.AttractiveRepulsiveAgent,
activation_regimes.Synchronous, None)
m.run_model()

In [156]:
m.raw_data

array([[ 0.26674687,  0.39115705,  0.51023365,  0.62822246,  0.74500196,
         0.83998898],
       [ 0.62027169,  0.69433416,  0.80045127,  0.84196051,  0.90849202,
         0.7835154 ],
       [-0.92707301, -1.        , -1.        , -1.        , -1.        ,
        -1.        ],
       [-0.26051624, -0.1947426 , -0.11356087, -0.02217315,  0.10179337,
         0.20676541],
       [-0.67206201, -0.67206201, -0.67206201, -0.67206201, -0.67206201,
        -0.67206201],
       [ 0.58365336,  0.60129207,  0.63897465,  0.58289127,  0.7428685 ,
         1.        ],
       [-0.02303976,  0.09626853,  0.2174727 ,  0.3398982 ,  0.41477803,
         0.52500159],
       [ 0.75409407,  0.68339873,  0.64571615,  0.52329065,  0.40165365,
         0.52663027],
       [ 0.80109296,  1.        ,  0.89181755,  1.        ,  1.        ,
         1.        ],
       [ 0.13619162,  0.05870177, -0.03967226, -0.05872145, -0.08635807,
        -0.20768549]])

In [157]:
ag = m.agents[0]
ag.unique_id, ag.o_i1

(0, 0.26674687212207493)

In [158]:
ag.neighbor_ids

array([5, 8], dtype=int64)

In [159]:
m.raw_data[(5,8),0]

array([0.58365336, 0.80109296])

in AttractiveRepulsive, the agent will always interact with the selected neighbor

In [160]:
constants.ATTRACTIVE_REPULSIVE_MU

0.5

in our formulation of the AttractiveRepulsive model, an agent is attracted by a neighbor if it is < 1 opinion unit away, unchanged if exactly 1 unit, and repulsed if > 1

In [161]:
ag.neighbor_ids[ag.neighbor_indexes_over_time_for_adoption[0]]

8

agent 8 is selected

In [162]:
np.abs(.80109-.26675)

0.53434

since the difference is < 1, agent 0 should be attracted to 8's opinion (move toward 0.80)

In [163]:
ag.o_i1 + constants.ATTRACTIVE_REPULSIVE_MU * (1 - np.abs(.80109-.26675)) * (.80109-.26675)

0.39115725432207493

In [164]:
m.raw_data[0, (0, 1)]

array([0.26674687, 0.39115705])

thus agent 0 is correctly influenced by agent 8

In [165]:
m.agents[2].neighbor_ids

array([5, 6], dtype=int64)

In [166]:
m.raw_data[(5,6),0]

array([ 0.58365336, -0.02303976])

In [167]:
m.agents[2].neighbor_indexes_over_time_for_adoption

array([0, 1, 0, 0, 0, 1])

from inspection of the raw_data table and these facts about Agent 2, we see it is repulsed every time (being clipped to -1 during its finalize() action). Agent 5 starts off at 0.58 while 2 starts at -0.92. Since 2 first selects 5, 2 is repulsed.

Agent 6 started at -0.023 so would have been close enough to attract 2 if 6 was selected on the first update. However, 6 became too far away from 2 after the first update, so 2 was repulsed when it did select 6 later.

### Random adoption agent

In [168]:
m = model.Model(1234, 5, ('scale_free', (10, 5)), agents.RandomAdoptionAgent,
activation_regimes.Synchronous, None)
m.run_model()

In [169]:
m.raw_data

array([[ 0.26674687,  0.80109296, -0.92707301,  0.58365336,  0.58365336,
         0.58365336],
       [ 0.62027169,  0.80109296, -0.92707301,  0.58365336,  0.58365336,
         0.58365336],
       [-0.92707301,  0.58365336,  0.58365336,  0.58365336, -0.92707301,
        -0.67206201],
       [-0.26051624,  0.58365336,  0.62027169,  0.62027169,  0.58365336,
         0.58365336],
       [-0.67206201, -0.67206201, -0.67206201, -0.67206201, -0.67206201,
        -0.67206201],
       [ 0.58365336,  0.62027169,  0.58365336, -0.92707301, -0.67206201,
        -0.67206201],
       [-0.02303976,  0.58365336,  0.58365336,  0.62027169,  0.58365336,
        -0.67206201],
       [ 0.75409407,  0.58365336,  0.62027169,  0.58365336,  0.58365336,
         0.58365336],
       [ 0.80109296, -0.92707301,  0.58365336,  0.58365336,  0.58365336,
        -0.92707301],
       [ 0.13619162, -0.67206201, -0.67206201,  0.58365336,  0.58365336,
        -0.67206201]])

In [170]:
ag = m.agents[0]
ag.unique_id, ag.o_i1

(0, 0.26674687212207493)

In [171]:
ag.neighbor_ids

array([5, 8], dtype=int64)

In [172]:
ag.neighbor_indexes_over_time_for_adoption

array([1, 1, 1, 1, 1, 0])

within this run, agent 0 should always adopt 8's opinion

In [173]:
m.raw_data[0, 1:]


array([ 0.80109296, -0.92707301,  0.58365336,  0.58365336,  0.58365336])

In [174]:
m.raw_data[8, :-1]

array([ 0.80109296, -0.92707301,  0.58365336,  0.58365336,  0.58365336])

these match, therefore agent 0 was updating correctly

### Final

from the above, all 5 agents have been face-validated for 1-2 time steps. we only used the Synchronous activation regime here because we do not easily capture the random update sequences for validation. however, the internal behavior of the agent classes is independent of the activation regime.

therefore, we are confident that the agent classes are functioning as designed and intended.

end//